[workspace]
members = [".", "xtask"]

[package]
name = "wasm-squeeze"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "UPX-like utility to create self-decompressable WASM-4 cartridges"
authors = ["Daria Sukhonina <dariasukhonina@gmail.com>"]
documentation = "https://docs.rs/wasm-squeeze"
repository = "https://github.com/zetanumbers/wasm-squeeze"
keywords = ["gamedev", "wasm4"]
categories = ["command-line-utilities", "development-tools::build-utils", "compression", "wasm"]

[dependencies]
anyhow = { version = "1.0.86", features = ["std"] }
clap = { version = "4.5.16", features = ["derive"] }
env_logger = { version = "0.11.5", default-features = false, features = ["auto-color"] }
log = "0.4.22"
upkr = "0.2.3"
wasm-encoder = { version = "0.214.0", features = ["wasmparser"] }
wasmparser = "0.214.0"
