[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive", "env"] }
common = { version = "0.1.0", path = "../common" }
walrus = "0.21.1"
